language: java

env:
    matrix:
    - ANDROID_IMGS=sysimg-16            ANDROID_TARGET=android-16  ANDROID_ABI=armeabi-v7a
#    - ANDROID_IMGS=sysimg-15            ANDROID_TARGET=android-16  ANDROID_ABI=armeabi-v7a
#    - ANDROID_IMGS=sysimg-17            ANDROID_TARGET=android-17  ANDROID_ABI=armeabi-v7a
    - ANDROID_IMGS=sysimg-19            ANDROID_TARGET=android-19  ANDROID_ABI=armeabi-v7a

before_install:
 
    - env

    - export INSTALL_PGK="libgd2-xpm ia32-libs ia32-libs-multiarch expect tree"
    - sudo apt-get update -qq
    - if [ `uname -m` = x86_64 ] ; then sudo apt-get install -qq --force-yes $INSTALL_PGK ; fi 

    - export ANDROID_SDK=android-sdk_r22.6-linux.tgz
    - wget http://dl.google.com/android/$ANDROID_SDK
    - tar -zxf $ANDROID_SDK 
    - export ANDROID_HOME=`pwd`/android-sdk-linux
    - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools

    - wget http://dl.google.com/android/adt/adt-bundle-linux-x86_64-20131030.zip
    - unzip adt-bundle-linux-x86_64-20131030.zip -d adt > /dev/null
    - export ANDROID_HOME=`pwd`/adt/adt-bundle-linux-x86_64-20131030/sdk
    - export PATH=${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools:$PATH
    # debug
    - which android
    - android list target
    - android list sdk --extended 
    - android list sdk --extended --all

#    - echo y | android update sdk --filter build-tools-19.0.3 --no-ui --force
#    - echo y | android update sdk --filter platform-tools --no-ui --force
#    - echo y | android update sdk --filter $ANDROID_TARGET --no-ui --force
#    - echo y | android update sdk --filter extra-android-support --no-ui --force
#    - echo y | android update sdk --filter $ANDROID_IMGS --no-ui --force
    - expect -d -c "spawn android --clear-cache -v update sdk --filter build-tools-19.0.3 --no-ui --force" android.update.sdk.expect
    - expect -d -c "spawn android --clear-cache -v update sdk --filter platform-tools --no-ui --force" android.update.sdk.expect
    - expect -d -c "spawn android --clear-cache -v update sdk --filter $ANDROID_TARGET --no-ui --force" android.update.sdk.expect
    - expect -d -c "spawn android --clear-cache -v update sdk --filter extra-android-support --no-ui --force" android.update.sdk.expect
    - expect -d -c "spawn android --clear-cache -v update sdk --filter $ANDROID_IMGS --no-ui --force" android.update.sdk.expect
    - expect -d -c "spawn android update sdk --filter platform-tools,build-tools-19.0.3,$ANDROID_TARGET,extra-android-support,$ANDROID_IMGS --no-ui --force" android.update.sdk.expect 
    - android list
    - export EMULATOR_NAME=test
    - tree $ANDROID_HOME/system-images
    - adb kill-server
    - adb start-server
    - expect -d -c "spawn android --clear-cache -v create avd -n $EMULATOR_NAME -t $ANDROID_TARGET --abi $ANDROID_ABI --force" android.create.avd.expect
#    - android create avd -n $EMULATOR_NAME -t $ANDROID_TARGET --abi $ANDROID_ABI --force

    # debug
    - android list avd
    - emulator -avd $EMULATOR_NAME -no-skin -no-audio -no-window &

# do this as later as possiable
#    - adb wait-for-device 
    - android update project -p . -t $ANDROID_TARGET

install:

script:
    - source  ./buildscript/lib/common.sh
    - set_as_lib_project . false
    - ant debug  

#    - adb wait-for-device 
    - wait_for_emulator

    - ant installd

    - cd test/unit
    - chmod a+x run_test.ant
    - adb devices
    - ./run_test.ant

    - cd ../..
    - cd test/uiautomator
    - chmod a+x run_test.sh
    - ./run_test.sh
